CanalTP\SamEcoreUserManagerBundle\Entity\User:
    type: entity
    table: public.t_user_usr
    fields:
        id:
            column: usr_id
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        firstName:
            column: usr_first_name
            type: string
            length: 255
        lastName:
            column: usr_last_name
            type: string
            length: 255
        username:
            column: usr_username
            type: string
            length: 255
        usernameCanonical:
            column: usr_username_canonical
            type: string
            length: 255
            unique: true
        email:
            column: usr_email
            type: string
            length: 255
        emailCanonical:
            column: usr_email_canonical
            type: string
            length: 255
            unique: true
        salt:
            column: usr_salt
            type: string
        password:
            column: usr_password
            type: string
        enabled:
            column: usr_enabled
            type: boolean
        locked:
            column: usr_locked
            type: boolean
        lastLogin:
            column: usr_last_login
            type: datetime
            nullable: true
        status:
            column: usr_status
            type: integer
        expired:
            column: usr_expired
            type: boolean
        expiresAt:
            column: usr_expires_at
            type: datetime
            nullable: true
        confirmationToken:
            column: usr_confirmation_token
            type: string
            nullable: true
        passwordRequestedAt:
            column: usr_password_requested_at
            type: datetime
            nullable: true
        credentialsExpired:
            column: usr_credentials_expired
            type: boolean
        credentialsExpireAt:
            column: usr_credentials_expire_at
            type: datetime
            nullable: true
    uniqueConstraints:
        username_idx:
            columns: [ usr_username, usr_username_canonical ]
        email_idx:
            columns: [ usr_email, usr_email_canonical ]
    manyToOne:
        customer:
            targetEntity: CanalTP\NmmPortalBundle\Entity\Customer
            inversedBy: users
            nullable: true
            joinColumn:
                name: cus_id
                referencedColumnName: cus_id
    manyToMany:
        userRoles:
            targetEntity: CanalTP\SamCoreBundle\Entity\Role
            inversedBy: users
            joinTable:
                name: public.tj_user_role_ur
                joinColumns:
                    usr_id:
                        referencedColumnName: usr_id
                inverseJoinColumns:
                    rol_id:
                        referencedColumnName: rol_id
