CanalTP\SamEcoreUserManagerBundle\Entity\User:
    type: entity
    table: t_user_usr
    fields:
        id:
            column: usr_id
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        firstName:
            column: usr_first_name
            type: string
            length: 255
        lastName:
            column: usr_last_name
            type: string
            length: 255
        username:
            column: usr_username
            type: string
            length: 255
        usernameCanonical:
            column: usr_username_canonical
            type: string
            length: 255
            unique: true
        email:
            column: usr_email
            type: string
            length: 255
        emailCanonical:
            column: usr_email_canonical
            type: string
            length: 255
            unique: true
        salt:
            column: usr_salt
            type: string
        password:
            column: usr_password
            type: string
        enabled:
            column: usr_enabled
            type: boolean
        locked:
            column: usr_locked
            type: boolean
        lastLogin:
            column: usr_last_login
            type: datetime
            nullable: true
        expired:
            column: usr_expired
            type: boolean
        expiresAt:
            column: usr_expires_at
            type: boolean
            nullable: true
        confirmationToken:
            column: usr_confirmation_token
            type: string
            nullable: true
        passwordRequestedAt:
            column: usr_password_requested_at
            type: datetime
            nullable: true
        credentialsExpired:
            column: usr_credentials_expired
            type: boolean
        credentialsExpireAt:
            column: usr_credentials_expire_at
            type: datetime
            nullable: true
    oneToMany:
        applicationRoles:
            targetEntity: CanalTP\SamCoreBundle\Entity\UserApplicationRole
            cascade:
              - persist
            mappedBy: user
    lifecycleCallbacks:
        postLoad:
            - onPostLoad
